---
- name: "Fetch File"
  hosts:
    - RS
  become: yes
  vars:
     path_tmp: '/tmp/rs'
     ds_home: '/opt/ds'
  tasks:
    - name: Deploy Replication Server
      ansible.builtin.script:
        cmd: ../scripts/setup-rs.sh
        register: results
    - name: debugmessage
      debug: 
       msg: results.stdout
      
