---
- name: "Create_folder"
  hosts:
    - RS
  become: yes

  tasks:
    - name: Createfolder
      file:
        path: "/home/folder1"
        state: directory
        script: ansible/scripts/download-rs.sh
      become: yes

  vars:
    folder_name: 'folder1'
    instance_http_ports:
      - 22
